name: Sync Content to Google Sheets

on:
  push:
    branches: [ main, master ]
    paths:
      - 'agroverse_schedule_till_easter.csv'
      - 'instagram_hashtags.csv'
      - 'sync_content_schedule.py'
      - 'sync_hashtags.py'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'agroverse_schedule_till_easter.csv'
      - 'instagram_hashtags.csv'
      - 'sync_content_schedule.py'
      - 'sync_hashtags.py'

jobs:
  sync-content-schedule:
    name: Sync Content Schedule
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create Google credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > google_credentials.json
        
    - name: Run Content Schedule Sync
      run: |
        python sync_content_schedule.py
        
    - name: Upload sync logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: content-schedule-sync-logs
        path: |
          *.log
        retention-days: 7

  sync-hashtags:
    name: Sync Hashtags
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create Google credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > google_credentials.json
        
    - name: Run Hashtags Sync
      run: |
        python sync_hashtags.py
        
    - name: Upload sync logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: hashtags-sync-logs
        path: |
          *.log
        retention-days: 7

  notify-completion:
    name: Notify Sync Completion
    runs-on: ubuntu-latest
    needs: [sync-content-schedule, sync-hashtags]
    if: always()
    
    steps:
    - name: Check job results
      run: |
        echo "Content Schedule Sync: ${{ needs.sync-content-schedule.result }}"
        echo "Hashtags Sync: ${{ needs.sync-hashtags.result }}"
        
        if [ "${{ needs.sync-content-schedule.result }}" = "success" ] || [ "${{ needs.sync-hashtags.result }}" = "success" ]; then
          echo "✅ At least one sync completed successfully"
          exit 0
        else
          echo "❌ All syncs failed or were skipped"
          exit 1
        fi
